apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: arkeonetwork
  namespace: argocd
spec: 
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators: 
  - git: 
      repoURL: https://github.com/arkeonetwork/helm-charts.git
      revision: HEAD
      directories: 
      - path: '*'
  template: 
    metadata: 
      name: '{{.path.basename}}'
    spec: 
      project: default
      sources: 
        - repoURL: https://github.com/arkeonetwork/helm-charts.git
          targetRevision: HEAD
          path: '{{.path.path}}'
          helm:
            parameters:
            - name: "etherscan_api_key"
              value: 
      destination: 
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy: 
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true