apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: daemons
  namespace: argocd
spec: 
  generators: 
  - git:
      repoURL: https://gitlab.com/thorchain/devops/node-launcher.git
      revision: HEAD
      directories:
      - path: '*'
      - path: '.*'
        exclude: true
      - path: ci
        exclude: true
      - path: loki
        exclude: true
      - path: docs
        exclude: true
      - path: mirroring
        exclude: true
      - path: prometheus
        exclude: true
      - path: scripts
        exclude: true
      - path: metrics-server
        exclude: true
      - path: kubernetes-dashboard
        exclude: true
  template: 
    metadata: 
      name: '{{path.basename}}'
    spec: 
      project: daemons
      sources: 
        - repoURL: https://gitlab.com/thorchain/devops/node-launcher.git
          targetRevision: HEAD
          path: '{{path}}'
          helm:
            parameters:
            - name: "persistence.storageClass"
              value: microk8s-hostpath
      destination: 
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy: 
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true